---
title: "Datahack@Yale: Yale Policy Lab"
author: "Team 14"
date: "2/18/2017"
output:
  pdf_document: default
---

```{r setup, include = FALSE}
library(YaleToolkit)
library(lubridate)
```

# Initial Exploration

```{r}

complaint <- read.csv("toy.complaint_data.csv", as.is = TRUE)
officer <- read.csv("toy.officer_data.csv", as.is = TRUE)
x <- merge(complaint, officer, by.x = "officer_id", by.y = "officer_id")
whatis(x) # 3884 officers, 5206 cases, 89 complaint categories, 16 ranks

```

# New Categorization
1: Use of Force/Verbal Abuse
2: Arrest/Locked up
3: Search
4: Failure to Provide Service
5: Operational Personnel Violations
6: Others

```{r}
# 12 Groups Based on Allegation Code
x$categorycode <- substring(x$complaintcategory, 1, 3)
table(x$categorycode)

# 6 Categories by Bocar
for (i in 1:nrow(x)) {
  if (x$categorycode[i] %in% c("01A","01B","01C","03E","04H","05A","05B","05C","05D","05E","05F","05G","05H","05J","05K","05L","05M","05N","05P","05Q","05T")) 
    x$categoryf[i] <- 1
  else if (x$categorycode[i] %in% c("04A","04B","04C","04D","04E","04F","04G","04J")) 
    x$categoryf[i] <- 2
  else if (x$categorycode[i] %in% c("03A","03B","03C","03D","03F","03G","03P")) 
    x$categoryf[i] <- 3
  else if (x$categorycode[i] %in% c("07A","07B","07C","07D","07E","07F","07T","10J","10U")) x$categoryf[i] <- 4
  else if (x$categorycode[i] %in% c("10A","10B","10C","10D","10E","10F","10G","10H","10K","10L","10M","10N","10P","10Q","10R","10S","10T","10V","10W","10X","10Y","10Z","12A","12B","12C","12D","12E","12F")) 
    x$categoryf[i] <- 5
  else 
    x$categoryf[i] <- 6
}

```

# Exploration of Variables
```{r}

head(x$incident_date, 20)
x$date <- substring(x$incident_date, 1, 11)
x$day <- as.numeric(substring(x$incident_date, 1, 2))
x$month <- substring(x$incident_date, 4, 6)
x$year <- as.numeric(substring(x$incident_date, 8, 11))
x$month <- gsub("Jan","1", x$month)
x$month <- gsub("Feb","2", x$month)
x$month <- gsub("Mar","3", x$month)
x$month <- gsub("Apr","4", x$month)
x$month <- gsub("May","5", x$month)
x$month <- gsub("Jun","6", x$month)
x$month <- gsub("Jul","7", x$month)
x$month <- gsub("Aug","8", x$month)
x$month <- gsub("Sep","9", x$month)
x$month <- gsub("Oct","10", x$month)
x$month <- gsub("Nov","11", x$month)
x$month <- gsub("Dec","12", x$month)
x$date <- paste(x$year, x$month, x$day, sep="-")

table(x$gender, x$categoryf)
table(x$age, x$categoryf)
table(x$rank, x$categoryf)

```



# Exploration of Complaint Cases
```{r}

s <- x[, c("officer_id", "categoryf")]

s1 <- small[s$categoryf==1,]
s2 <- small[s$categoryf==2,]
s3 <- small[s$categoryf==3,]
s4 <- small[s$categoryf==4,]
s5 <- small[s$categoryf==5,]
s6 <- small[s$categoryf==6,]

length(unique(s1$officer_id)) # 1663 unique / 3388 cases
length(unique(s2$officer_id)) # 704 unique / 899 cases
length(unique(s3$officer_id)) # 2260 unique / 5441 cases
length(unique(s4$officer_id)) # 1284 unique / 1968 cases
length(unique(s5$officer_id)) # 921 unique / 1246 cases
length(unique(s6$officer_id)) # 688 unique / 898 cases

table(tapply(s1$categoryf, s1$officer_id, length))
table(tapply(s2$categoryf, s2$officer_id, length))
table(tapply(s3$categoryf, s3$officer_id, length))
table(tapply(s4$categoryf, s4$officer_id, length))
table(tapply(s5$categoryf, s5$officer_id, length))
table(tapply(s6$categoryf, s6$officer_id, length))

plot(tapply(s1$categoryf, s1$officer_id, length))
plot(tapply(s2$categoryf, s2$officer_id, length))
plot(tapply(s3$categoryf, s3$officer_id, length))
plot(tapply(s4$categoryf, s4$officer_id, length))
plot(tapply(s5$categoryf, s5$officer_id, length))
plot(tapply(s6$categoryf, s6$officer_id, length))

```

# Officers with Multiple Complaint Cases
```{r}

# number of cases per officer
table(table(x$officer_id))
plot(table(table(x$officer_id)))
y <- aggregate(x$officer_id, by = x['officer_id'], length)

table(x[x$officer_id==which(y$x == 42), ]$categoryf) # list of complaint by an officer who had 42 complaints in total
```

# R Visualization
```{r}


```